Ruby group capstone - Catalog of my things
yashodhicy/RubyCapstone pull request #40
Opened 2023-08-10 12:52 UTC by yashodhicy

In this milestone, we add classes that match the below UML class diagram.

![catalog_of_my_things](https://github.com/yashodhicy/RubyCapstone/assets/116276432/a3c9b648-bf28-4627-955b-4c912b3dd62c)

🌺 Each class from the [UML class diagram](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/images/catalog_of_my_things.png) should be created in a separate .rb file.
🌺 All associations (1-to-many relationships) and aggregations (parent-child relationships) between classes should be implemented.
🌺 All properties visible in the diagram should be defined and set up in the constructor method. Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.
🌺 add_item method (in all classes that have that method)

- [x] should take an instance of the Item class as an input.
- [x] should add the input item to the collection of items.
- [x] should add self as a property of the item object (by using the correct setter from the item object).

🌺can_be_archived?() in the Item class

- [x] should return true if published_date is older than 10 years.
- [x] Otherwise, it should return false.

🌺move_to_archive() in the Item class

- [x] should reuse can_be_archived?() method.
- [x] should change the archived property to true if the result of the can_be_archived?() method is true.
- [x] should do nothing if the result of the can_be_archived?() method is false.

🌺can_be_archived?() in the Book class

- [x] should override the method from the parent class.
- [x] should return true if parent's method returns true OR if cover_state equals to "bad".
- [x] otherwise, it should return false.

🌺can_be_archived?() in the MusicAlbum class

- [x] should override the method from the parent class.
- [x] should return true if parent's method returns true AND if on_spotify equals true.
- [x] otherwise, it should return false.

🌺can_be_archived?() in the Movie class

- [x] should override the method from the parent class.
- [x] should return true if parent's method returns true OR if silent equals true.
- [x] otherwise, it should return false.

🌺can_be_archived?() in the Game class

- [x] should override the method from the parent class.
- [x] should return true if parent's method returns true AND if last_played_at is older than 2 years.
- [x] otherwise, it should return false.

🌺Add unit tests for all implemented methods.

**User interface**

🌺Create a main.rb file that will serve as your console app entry point.

- [x] Present the user with a list of options to perform.
- [x] Let users choose an option.
- [x] If needed, ask for parameters for the option.
- [x] Have a way to quit the app.

🌺The following options should be available:

- List all books
- List all music albums
- List all movies
- List of games
- List all genres (e.g 'Comedy', 'Thriller')
- List all labels (e.g. 'Gift', 'New')
- List all authors (e.g. 'Stephen King')
- List all sources (e.g. 'From a friend', 'Online shop')
- Add a book
- Add a music album
- Add a movie
- Add a game

🌺All data should be preserved by saving collections in .json files.

**Database**
🌺Create a schema.sql file with tables that will be analogical to the structure of the classes in-app.

2023-08-10 15:46 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi TEAM
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![0bd223a2b156e0eaf61a713e84c3d3b7](https://user-images.githubusercontent.com/57408419/255594021-109e7375-12de-4f5b-9e29-79eefc52e35a.gif)



## To highlight :champagne: 

- All tests are passing :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-10 15:46 UTC, joel-kalema commented on classes/MusicAlbum/music_album.rb
> +    @on_spotify = on_spotify
- [ ] Good job implementing `MusicAlbum` class, however, currently we are not saving data for the `music_album` and `genres`.  Kindly  make sure to save data after adding the `music album`  and `genres` as it is [required](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things.md#:~:text=All%20data%20should%20be%20preserved%20by%20saving%20collections%20in%20.json%20files.) to preserve data 👍 

![Screenshot 2023-08-10 170806](https://github.com/yashodhicy/RubyCapstone/assets/57408419/d07f8373-e0b7-494a-8fba-1eeee9b12ee7)

2023-08-10 20:07 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @yashodhicy, @Shaheryar0054 & @AliShahSafdari 

Great work on making the changes requested by a previous reviewer 👏! I really appreciate the effort you put in!  **_However, there are few this that still need to be fixed. But you are almost there!_** 💪 🏁

![so close](https://media.tenor.com/3sCHnD_x2RIAAAAC/almost-there.gif)


## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Data is preserved in JSON files
- ✅ All tests are passing
- ✅ Descriptive PR and README file
- ✅ Relationships are handled well

## Required Changes 🛑

_Please check the comments under the review._

## Optional suggestions ❕

N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-11 05:20 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @team, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## Highlights
-  Implemented required changes. :heavy_check_mark: 
-  Data preserved properly. :heavy_check_mark: 
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/4799731d86dd0d52a0bb7e22af48077bd16556ee26061146e987e9a98d36ee0d/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-08-11 05:30 UTC, merged